"""Interactive and one-shot wizard that enables remote dispatch for a ROBOT.md robot."""

from __future__ import annotations

import os
import secrets
import shutil
import sys
import tempfile
from dataclasses import dataclass
from pathlib import Path


class _Precondition(Exception):
    """Precondition failure with a user-facing message."""


@dataclass
class WizardConfig:
    bind: str = "127.0.0.1"
    port: int = 8080
    generate_actuate: bool = True
    generate_read: bool = False
    systemd_print: bool = False
    tailscale_print: bool = False


def _generate_tokens(cfg: WizardConfig) -> tuple[str, str | None]:
    actuate = secrets.token_urlsafe(32) if cfg.generate_actuate else ""
    read = secrets.token_urlsafe(32) if cfg.generate_read else None
    return actuate, read


def _atomic_write(path: Path, content: str, mode: int) -> None:
    """Write `content` to `path` atomically. On failure, leaves no partial files."""
    target_dir = path.parent
    fd, tmp_name = tempfile.mkstemp(prefix=f".{path.name}.", dir=str(target_dir))
    try:
        with os.fdopen(fd, "w") as f:
            f.write(content)
        os.chmod(tmp_name, mode)
        os.replace(tmp_name, path)
    except Exception:
        try:
            os.unlink(tmp_name)
        except FileNotFoundError:
            pass
        raise


def _write_bearers_yaml(path: Path, *, actuate_token: str, read_token: str | None) -> None:
    lines = [
        "# robot-md-dispatcher bearers — generated by `init`.",
        "# Rotate by replacing tokens and restarting the service.",
    ]
    if actuate_token:
        lines.extend([
            f"- token: {actuate_token}",
            "  tier: actuate",
            "  caller: actuate-default",
        ])
    if read_token:
        lines.extend([
            f"- token: {read_token}",
            "  tier: read",
            "  caller: read-default",
        ])
    content = "\n".join(lines) + "\n"
    _atomic_write(path, content, mode=0o600)


def _write_env(path: Path) -> None:
    content = (
        "ROBOT_MD_PATH=./ROBOT.md\n"
        "ROBOT_MD_BEARERS_FILE=./bearers.yaml\n"
        "ROBOT_MD_MCP_COMMAND=robot-md-mcp\n"
        "ROBOT_MD_LOG_LEVEL=INFO\n"
    )
    _atomic_write(path, content, mode=0o644)


def _write_dispatch_test_sh(
    path: Path, *, actuate_token: str, bind: str, port: int
) -> None:
    content = f"""#!/usr/bin/env bash
# robot-md-dispatcher smoke test — generated by `init`.
set -euo pipefail

if [[ -z "${{ANTHROPIC_API_KEY:-}}" ]]; then
    echo "error: export ANTHROPIC_API_KEY=sk-ant-... before running this script" >&2
    exit 1
fi

curl -N http://{bind}:{port}/dispatch \\
    -H "Authorization: Bearer {actuate_token}" \\
    -H "X-Anthropic-Api-Key: ${{ANTHROPIC_API_KEY}}" \\
    -H "Content-Type: application/json" \\
    -d '{{"goal": "call render and describe the robot"}}'
"""
    _atomic_write(path, content, mode=0o700)


def _check_robot_md_exists(cwd: Path) -> Path:
    robot_md = cwd / "ROBOT.md"
    if not robot_md.is_file():
        raise _Precondition(
            f"No ROBOT.md in {cwd}. Run 'robot-md init' or 'castor init' first."
        )
    return robot_md


def _validate_robot_md(robot_md: Path) -> str:
    """Validate ROBOT.md and return the robot name. Raises _Precondition on failure."""
    try:
        from robot_md.parser import ParseError, parse_file
        from robot_md.validate import VALID, validate
    except ImportError as e:
        raise _Precondition(
            "robot-md package not installed. Install with 'pip install robot-md'."
        ) from e

    try:
        parsed = parse_file(robot_md)
    except ParseError as e:
        raise _Precondition(
            f"ROBOT.md parse error: {e}\n"
            "Fix ROBOT.md and re-run 'robot-md-dispatcher init'."
        ) from e

    result = validate(parsed)
    if result.code != VALID:
        msg_lines = ["ROBOT.md validation failed:"]
        for err in result.errors:
            msg_lines.append(f"  - {err}")
        msg_lines.append("Fix ROBOT.md and re-run 'robot-md-dispatcher init'.")
        raise _Precondition("\n".join(msg_lines))

    # RCAN v3 schema: robot name lives at metadata.robot_name, not top-level name.
    metadata = parsed.frontmatter.get("metadata") or {}
    return str(metadata.get("robot_name", "unknown"))


def _check_mcp_on_path() -> None:
    if shutil.which("robot-md-mcp") is None:
        raise _Precondition(
            "robot-md-mcp not found on PATH. Install with "
            "'npm install -g robot-md-mcp' (Node) or 'pip install robot-md' "
            "(Python wrapper)."
        )


def _check_no_existing_files(cwd: Path) -> None:
    for name in ("bearers.yaml", ".env"):
        if (cwd / name).exists():
            raise _Precondition(
                f"./{name} already exists. Use 'init --force' to regenerate tokens "
                "(this invalidates the old ones)."
            )


def run(
    *,
    interactive: bool,
    cwd: Path,
    force: bool = False,
    no_token_stdout: bool = False,
) -> int:
    """Run the init wizard. Returns a process exit code."""
    try:
        robot_md = _check_robot_md_exists(cwd)
        robot_name = _validate_robot_md(robot_md)
        _check_mcp_on_path()
        if not force:
            _check_no_existing_files(cwd)
    except _Precondition as e:
        print(str(e), file=sys.stderr)
        return 1

    cfg = WizardConfig()  # interactive-mode prompts come in later tasks
    actuate_token, read_token = _generate_tokens(cfg)

    _write_bearers_yaml(
        cwd / "bearers.yaml",
        actuate_token=actuate_token,
        read_token=read_token,
    )
    _write_env(cwd / ".env")
    if actuate_token:
        _write_dispatch_test_sh(
            cwd / "dispatch-test.sh",
            actuate_token=actuate_token,
            bind=cfg.bind,
            port=cfg.port,
        )

    _print_next_steps(
        cfg=cfg,
        robot_name=robot_name,
        actuate_token=actuate_token,
        no_token_stdout=no_token_stdout,
    )
    return 0


def _print_next_steps(
    *,
    cfg: WizardConfig,
    robot_name: str,
    actuate_token: str,
    no_token_stdout: bool,
) -> None:
    print(f"Found ROBOT.md for {robot_name!r}.")
    print(
        f"Writing: bind {cfg.bind}:{cfg.port}, 1 actuate token, dev-mode (./ files)."
    )
    print("  ./bearers.yaml")
    print("  ./.env")
    if actuate_token:
        print("  ./dispatch-test.sh")

    if no_token_stdout:
        print()
        print("Actuate token written to ./bearers.yaml (0600). Open the file to read it.")
    else:
        print()
        print("Actuate token (save now — not persisted anywhere else):")
        print(f"  {actuate_token}")

    print()
    print("Next:")
    print(
        f"  robot-md-dispatcher serve --bearers ./bearers.yaml "
        f"--robot-md ./ROBOT.md"
    )
    print()
    print("Tip: add bearers.yaml, .env, dispatch-test.sh to .gitignore")
