"""Interactive and one-shot wizard that enables remote dispatch for a ROBOT.md robot."""

from __future__ import annotations

import contextlib
import os
import secrets
import shutil
import sys
import tempfile
from dataclasses import dataclass
from pathlib import Path


class _Precondition(Exception):
    """Precondition failure with a user-facing message."""


@dataclass
class WizardConfig:
    bind: str = "127.0.0.1"
    port: int = 8080
    generate_actuate: bool = True
    generate_read: bool = False
    systemd_print: bool = False
    tailscale_print: bool = False


def _generate_tokens(cfg: WizardConfig) -> tuple[str, str | None]:
    actuate = secrets.token_urlsafe(32) if cfg.generate_actuate else ""
    read = secrets.token_urlsafe(32) if cfg.generate_read else None
    return actuate, read


def _atomic_write(path: Path, content: str, mode: int) -> None:
    """Write `content` to `path` atomically. On failure, leaves no partial files."""
    target_dir = path.parent
    fd, tmp_name = tempfile.mkstemp(prefix=f".{path.name}.", dir=str(target_dir))
    try:
        with os.fdopen(fd, "w") as f:
            f.write(content)
        os.chmod(tmp_name, mode)
        os.replace(tmp_name, path)
    except Exception:
        with contextlib.suppress(FileNotFoundError):
            os.unlink(tmp_name)
        raise


def _write_bearers_yaml(path: Path, *, actuate_token: str, read_token: str | None) -> None:
    lines = [
        "# robot-md-gateway bearers — generated by `init`.",
        "# Rotate by replacing tokens and restarting the service.",
    ]
    if actuate_token:
        lines.extend([
            f"- token: {actuate_token}",
            "  tier: actuate",
            "  caller: actuate-default",
        ])
    if read_token:
        lines.extend([
            f"- token: {read_token}",
            "  tier: read",
            "  caller: read-default",
        ])
    content = "\n".join(lines) + "\n"
    _atomic_write(path, content, mode=0o600)


def _write_env(path: Path) -> None:
    content = (
        "ROBOT_MD_PATH=./ROBOT.md\n"
        "ROBOT_MD_BEARERS_FILE=./bearers.yaml\n"
        "ROBOT_MD_MCP_COMMAND=robot-md-mcp\n"
        "ROBOT_MD_LOG_LEVEL=INFO\n"
    )
    _atomic_write(path, content, mode=0o644)


def _write_dispatch_test_sh(
    path: Path, *, actuate_token: str, bind: str, port: int
) -> None:
    content = f"""#!/usr/bin/env bash
# robot-md-gateway smoke test — generated by `init`.
set -euo pipefail

if [[ -z "${{ANTHROPIC_API_KEY:-}}" ]]; then
    echo "error: export ANTHROPIC_API_KEY=sk-ant-... before running this script" >&2
    exit 1
fi

curl -N http://{bind}:{port}/dispatch \\
    -H "Authorization: Bearer {actuate_token}" \\
    -H "X-Anthropic-Api-Key: ${{ANTHROPIC_API_KEY}}" \\
    -H "Content-Type: application/json" \\
    -d '{{"goal": "call render and describe the robot"}}'
"""
    _atomic_write(path, content, mode=0o700)


def _check_robot_md_exists(cwd: Path) -> Path:
    robot_md = cwd / "ROBOT.md"
    if not robot_md.is_file():
        raise _Precondition(
            f"No ROBOT.md in {cwd}. Run 'robot-md init' or 'castor init' first."
        )
    return robot_md


def _validate_robot_md(robot_md: Path) -> str:
    """Validate ROBOT.md and return the robot name. Raises _Precondition on failure."""
    try:
        from robot_md.parser import ParseError, parse_file
        from robot_md.validate import VALID, validate
    except ImportError as e:
        raise _Precondition(
            "robot-md package not installed. Install with 'pip install robot-md'."
        ) from e

    try:
        parsed = parse_file(robot_md)
    except ParseError as e:
        raise _Precondition(
            f"ROBOT.md parse error: {e}\n"
            "Fix ROBOT.md and re-run 'robot-md-gateway init'."
        ) from e

    result = validate(parsed)
    if result.code != VALID:
        msg_lines = ["ROBOT.md validation failed:"]
        for err in result.errors:
            msg_lines.append(f"  - {err}")
        msg_lines.append("Fix ROBOT.md and re-run 'robot-md-gateway init'.")
        raise _Precondition("\n".join(msg_lines))

    # RCAN v3 schema: robot name lives at metadata.robot_name, not top-level name.
    metadata = parsed.frontmatter.get("metadata") or {}
    return str(metadata.get("robot_name", "unknown"))


def _check_mcp_on_path() -> None:
    if shutil.which("robot-md-mcp") is None:
        raise _Precondition(
            "robot-md-mcp not found on PATH. Install with "
            "'npm install -g robot-md-mcp' (Node) or 'pip install robot-md' "
            "(Python wrapper)."
        )


def _box(title: str, lines: list[str]) -> str:
    width = 64
    top = f"╭─ {title} " + "─" * (width - len(title) - 4) + "╮"
    bot = "╰" + "─" * (width - 1) + "╯"
    body = "\n".join(f"│ {line.ljust(width - 3)}│" for line in lines)
    return f"{top}\n{body}\n{bot}"


def _ask_yes_no(question: str, default: bool) -> bool:
    suffix = "[Y/n]" if default else "[y/N]"
    raw = input(f"{question} {suffix}: ").strip().lower()
    if not raw:
        return default
    return raw in ("y", "yes")


def _ask_text(question: str, default: str) -> str:
    raw = input(f"{question} [{default}]: ").strip()
    return raw or default


def _ask_int(question: str, default: int) -> int:
    while True:
        raw = input(f"{question} [{default}]: ").strip()
        if not raw:
            return default
        try:
            return int(raw)
        except ValueError:
            print(f"  not an integer: {raw!r}", file=sys.stderr)


def _prompt_config(robot_name: str) -> WizardConfig | None:
    """Interactive prompts. Returns None if user declined the initial confirm."""
    print(_box(
        "What this does",
        [
            "Writes a bearers.yaml (access tokens) and a .env (paths +",
            "MCP command) next to your ROBOT.md. Does not start the",
            "service or open network ports.",
        ],
    ))
    if not _ask_yes_no(f"Enable remote dispatch for {robot_name!r}?", default=True):
        print("No changes made.")
        return None

    print(_box(
        "Bind address",
        [
            "Local address the gateway listens on. Use 127.0.0.1 if",
            "you'll front this with Tailscale Funnel or a reverse proxy.",
            "Use 0.0.0.0 only if your network boundary is hardened.",
        ],
    ))
    bind = _ask_text("Bind address", default="127.0.0.1")

    print(_box(
        "Port",
        ["TCP port the HTTP server binds to. 8080 is the default."],
    ))
    port = _ask_int("Port", default=8080)

    print(_box(
        "Bearer tokens",
        [
            "Callers authenticate with a bearer token. Each token has a",
            "tier: 'actuate' can drive the robot; 'read' can only call",
            "observation tools (render, validate, get_*, list_*, ...).",
        ],
    ))
    gen_actuate = _ask_yes_no("Generate an actuate-tier token?", default=True)
    gen_read = _ask_yes_no("Also generate a read-tier token?", default=False)

    print(_box(
        "Production install (systemd)",
        [
            "For long-running hosts, install as a systemd service under",
            "a dedicated 'robot' user with MemoryMax/CPUQuota limits.",
            "Requires sudo. This wizard PRINTS the commands; it does NOT",
            "run sudo on your behalf.",
        ],
    ))
    systemd = _ask_yes_no("Install as systemd service?", default=False)

    print(_box(
        "Tailscale Funnel",
        [
            "Named, revocable, TLS-terminated public URL via your",
            "tailnet. We'll print the two setup commands; we won't run",
            "them (they need your interactive auth).",
        ],
    ))
    tailscale = _ask_yes_no("Print Tailscale Funnel setup commands?", default=False)

    return WizardConfig(
        bind=bind,
        port=port,
        generate_actuate=gen_actuate,
        generate_read=gen_read,
        systemd_print=systemd,
        tailscale_print=tailscale,
    )


def _rollback(created_paths: list[Path]) -> None:
    for path in created_paths:
        with contextlib.suppress(FileNotFoundError):
            path.unlink()


def _check_no_existing_files(cwd: Path) -> None:
    for name in ("bearers.yaml", ".env", "dispatch-test.sh"):
        if (cwd / name).exists():
            raise _Precondition(
                f"./{name} already exists. Use 'init --force' to regenerate "
                "(this invalidates the old tokens)."
            )


def run(
    *,
    interactive: bool,
    cwd: Path,
    force: bool = False,
    no_token_stdout: bool = False,
) -> int:
    """Run the init wizard. Returns a process exit code."""
    try:
        robot_md = _check_robot_md_exists(cwd)
        robot_name = _validate_robot_md(robot_md)
        _check_mcp_on_path()
        if not force:
            _check_no_existing_files(cwd)
    except _Precondition as e:
        print(str(e), file=sys.stderr)
        return 1

    if interactive and not sys.stdin.isatty():
        print(
            "Interactive mode requires a TTY. Use 'init --yes' for defaults, "
            "or run from a terminal.",
            file=sys.stderr,
        )
        return 1

    if interactive:
        try:
            cfg = _prompt_config(robot_name)
        except KeyboardInterrupt:
            print("\nAborted. No files written.", file=sys.stderr)
            return 130
        if cfg is None:
            return 0  # user declined the initial confirm; no changes made
    else:
        cfg = WizardConfig()

    actuate_token, read_token = _generate_tokens(cfg)

    created: list[Path] = []
    try:
        bearers_path = cwd / "bearers.yaml"
        _write_bearers_yaml(
            bearers_path,
            actuate_token=actuate_token,
            read_token=read_token,
        )
        created.append(bearers_path)

        env_path = cwd / ".env"
        _write_env(env_path)
        created.append(env_path)

        if actuate_token:
            test_path = cwd / "dispatch-test.sh"
            _write_dispatch_test_sh(
                test_path,
                actuate_token=actuate_token,
                bind=cfg.bind,
                port=cfg.port,
            )
            created.append(test_path)
    except OSError as e:
        _rollback(created)
        print(f"Write failed: {e}", file=sys.stderr)
        return 1

    _print_next_steps(
        cfg=cfg,
        robot_name=robot_name,
        actuate_token=actuate_token,
        no_token_stdout=no_token_stdout,
    )
    return 0


def _print_next_steps(
    *,
    cfg: WizardConfig,
    robot_name: str,
    actuate_token: str,
    no_token_stdout: bool,
) -> None:
    print(f"Found ROBOT.md for {robot_name!r}.")
    print(
        f"Writing: bind {cfg.bind}:{cfg.port}, 1 actuate token, dev-mode (./ files)."
    )
    print("  ./bearers.yaml")
    print("  ./.env")
    if actuate_token:
        print("  ./dispatch-test.sh")

    if no_token_stdout:
        print()
        print("Actuate token written to ./bearers.yaml (0600). Open the file to read it.")
    else:
        print()
        print("Actuate token (save now — not persisted anywhere else):")
        print(f"  {actuate_token}")

    print()
    print("Next:")
    print(
        "  robot-md-gateway serve --bearers ./bearers.yaml "
        "--robot-md ./ROBOT.md"
    )

    if cfg.systemd_print:
        print()
        print("Production install (run these):")
        print("  sudo ./systemd/install.sh")
        print("  sudo cp ./bearers.yaml ./.env /etc/robot-md-dispatcher/")
        print("  sudo cp ./ROBOT.md /etc/robot-md-dispatcher/ROBOT.md")
        print("  sudo systemctl daemon-reload && sudo systemctl enable --now robot-md-dispatcher")

    if cfg.tailscale_print:
        print()
        print("Tailscale Funnel exposure (run these):")
        print(f"  tailscale serve --bg --https=443 http://{cfg.bind}:{cfg.port}")
        print("  tailscale funnel 443 on")

    print()
    print("Tip: add bearers.yaml, .env, dispatch-test.sh to .gitignore")
